import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/link';
import styles from '../../styles/Home.module.css'


export default function Detail() {
    const router = useRouter();
    const productId = router.query.productId;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/'><button>{"<--"} Home</button></Link>
        <h1 className={styles.title}>
          Product Detail Page:  {productId}
        </h1>
      </main>
    </div>
  )
}
