import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home({products}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ul>
          <li><Link href="/render-modes/graphql-client">GraphQL Client</Link></li>
          <li><Link href="/render-modes/graphql-ssr">GraphQL SSR</Link></li>
          <li><Link href="/render-modes/graphql-static">GraphQL Static</Link></li>

          <li><Link href="/detail/123">Product Detail Page</Link></li>
          <li><Link href="/mode/damen/shirts/adidas/red/size-m/">Dynamic ISR route example</Link></li>
          <li><Link href="/article-1/">Route priority on static pages</Link></li>
        </ul>
      </main>
    </div>
  )
}
