import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../../styles/Home.module.css'

import client from '../../apollo-client';

import {GET_PRODUCTS} from "../../graphql/Queries";


import ClientOnly from '../../components/ClientOnly'
import Reviews from '../../components/Reviews';

export async function getStaticProps() {

  const {data} = await client.query(GET_PRODUCTS);

  return {
    props: {
      products: data.products
    }
  };
}

const Product = ({product}) => {
  const {name, price, category} = product;
  return (
    <div className={`${styles.card} ${styles.product}`}>
      <h3>{name}</h3>
      <h4>{price}</h4>
      <p>{category.name}</p>
    </div>
  );
};

export default function Home({products}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/'><button>{"<--"} Home</button></Link>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js, Static!</a>
        </h1>

        <section className={`${styles.grid} ${styles.products}`}>
          {products && products.map((p) => (<Product key={p.id} product={p}/>))}
        </section>

        <ClientOnly>
          <h3>Client Side reviews</h3>
          <Reviews />
        </ClientOnly>
        
        
      </main>
    </div>
  )
}
